sudo: yes
language: java
cache:
  directories:
    - .autoconf
    - $HOME/.m2
services:
  - docker
jdk:
  - openjdk8
branches:
  only:
    - master
before_install:
  - mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings.xml
  - cd $TRAVIS_BUILD_DIR
script:
  - "[ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ] && mvn -P travis clean deploy || mvn -P travis clean install"
after_success:
  - mvn coveralls:report
env:
  global:
